### ISSUE TITLE
New maintained branch for gettext

### ISSUE THREAD

**Issue by dgilperez** [cameel/gettext#3]
Hi cameel!

It seems that gettext is been maintained again, by @ruby-gettext. You can check github.com/ruby-gettext/gettext .

We have been using your branch without further trouble, after you fixed it for ruby 1.9.2 a few months ago. I just tried it that branch and everything appears to be working. 

I just wanted to let you know, both for your information (in case you don't know yet) and I thought you might want to check if your changes are included in this new distribution / pull request those.

Regards !

David

**Comment by cameel** [comment]
Thanks for the info. I have seen it a few weeks ago and I am going to switch my projects to it in the near future. At a glance it seems that the maintainer did not pull the fixes from this fork but they were quite simple so if it works for you, it's very likely that he has fixed them on his own. If it turns out that something is missing, I'll definitely submit a pull request.
